language: node_js
node_js:
  - "11"

sudo: false

env:
  - NODE_ENV=development

script:
  - "npm test"

after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

